config/routes.rb
Testie::Application.routes.draw do
  resources :partidas

  resources :parteobras

  

end

app/models/parteobra.rb
class Parteobra < ActiveRecord::Base
  has_many :partidas
  accepts_nested_attributes_for :partidas
end

app/models/partida.rb
class Partida < ActiveRecord::Base
  belongs_to :parteobra
  validates_presence_of :lista_id, :message => ":Escriba el list_id"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/parteobras_controller.rb
class ParteobrasController < ApplicationController
  before_action :set_parteobra, only: [:show, :edit, :update, :destroy]

  # GET /parteobras
  # GET /parteobras.json
  def index
    @parteobras = Parteobra.all
  end

  # GET /parteobras/1
  # GET /parteobras/1.json
  def show
  end

  # GET /parteobras/new
  def new
    @parteobra = Parteobra.new
  end

  # GET /parteobras/1/edit
  def edit
  end

  # POST /parteobras
  # POST /parteobras.json
  def create
    @parteobra = Parteobra.new(parteobra_params)

    respond_to do |format|
      if @parteobra.save
        format.html { redirect_to @parteobra, notice: 'Parteobra was successfully created.' }
        format.json { render action: 'show', status: :created, location: @parteobra }
      else
        format.html { render action: 'new' }
        format.json { render json: @parteobra.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parteobras/1
  # PATCH/PUT /parteobras/1.json
  def update
    respond_to do |format|
      if @parteobra.update(parteobra_params)
        format.html { redirect_to @parteobra, notice: 'Parteobra was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @parteobra.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parteobras/1
  # DELETE /parteobras/1.json
  def destroy
    @parteobra.destroy
    respond_to do |format|
      format.html { redirect_to parteobras_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parteobra
      @parteobra = Parteobra.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def parteobra_params
      params.require(:parteobra).permit(:nombre)
    end
end

app/controllers/partidas_controller.rb
class PartidasController < ApplicationController
  before_action :set_partida, only: [:show, :edit, :update, :destroy]

  # GET /partidas
  # GET /partidas.json
  def index
    @partidas = Partida.all
  end

  # GET /partidas/1
  # GET /partidas/1.json
  def show
  end

  # GET /partidas/new
  def new
    @partida = Partida.new
  end

  # GET /partidas/1/edit
  def edit
  end

  # POST /partidas
  # POST /partidas.json
  def create
    @partida = Partida.new(partida_params)

    respond_to do |format|
      if @partida.save
        format.html { redirect_to @partida, notice: 'Partida was successfully created.' }
        format.json { render action: 'show', status: :created, location: @partida }
      else
        format.html { render action: 'new' }
        format.json { render json: @partida.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /partidas/1
  # PATCH/PUT /partidas/1.json
  def update
    respond_to do |format|
      if @partida.update(partida_params)
        format.html { redirect_to @partida, notice: 'Partida was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @partida.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /partidas/1
  # DELETE /partidas/1.json
  def destroy
    @partida.destroy
    respond_to do |format|
      format.html { redirect_to partidas_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_partida
      @partida = Partida.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def partida_params
      params.require(:partida).permit(:diametro, :parteobra_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/parteobras_helper.rb
module ParteobrasHelper
end

app/helpers/partidas_helper.rb
module PartidasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Testie</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/parteobras/_form.html.erb
<%= form_for(@parteobra) do |f| %>
  <% if @parteobra.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@parteobra.errors.count, "error") %> prohibited this parteobra from being saved:</h2>

      <ul>
      <% @parteobra.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/parteobras/edit.html.erb
<h1>Editing parteobra</h1>

<%= render 'form' %>

<%= link_to 'Show', @parteobra %> |
<%= link_to 'Back', parteobras_path %>

app/views/parteobras/index.html.erb
<h1>Listing parteobras</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @parteobras.each do |parteobra| %>
      <tr>
        <td><%= parteobra.nombre %></td>
        <td><%= link_to 'Show', parteobra %></td>
        <td><%= link_to 'Edit', edit_parteobra_path(parteobra) %></td>
        <td><%= link_to 'Destroy', parteobra, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Parteobra', new_parteobra_path %>

app/views/parteobras/new.html.erb
<h1>New parteobra</h1>

<%= render 'form' %>

<%= link_to 'Back', parteobras_path %>

app/views/parteobras/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @parteobra.nombre %>
</p>

<%= link_to 'Edit', edit_parteobra_path(@parteobra) %> |
<%= link_to 'Back', parteobras_path %>

app/views/partidas/_form.html.erb
<%= form_for(@partida) do |f| %>
  <% if @partida.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@partida.errors.count, "error") %> prohibited this partida from being saved:</h2>

      <ul>
      <% @partida.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :diametro %><br>
    <%= f.text_field :diametro %>
  </div>
  <div class="field">
    <%= f.label :parteobra %><br>
    <%= f.text_field :parteobra %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/partidas/edit.html.erb
<h1>Editing partida</h1>

<%= render 'form' %>

<%= link_to 'Show', @partida %> |
<%= link_to 'Back', partidas_path %>

app/views/partidas/index.html.erb
<h1>Listing partidas</h1>

<table>
  <thead>
    <tr>
      <th>Diametro</th>
      <th>Parteobra</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @partidas.each do |partida| %>
      <tr>
        <td><%= partida.diametro %></td>
        <td><%= partida.parteobra %></td>
        <td><%= link_to 'Show', partida %></td>
        <td><%= link_to 'Edit', edit_partida_path(partida) %></td>
        <td><%= link_to 'Destroy', partida, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Partida', new_partida_path %>

app/views/partidas/new.html.erb
<h1>New partida</h1>

<%= render 'form' %>

<%= link_to 'Back', partidas_path %>

app/views/partidas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Diametro:</strong>
  <%= @partida.diametro %>
</p>

<p>
  <strong>Parteobra:</strong>
  <%= @partida.parteobra %>
</p>

<%= link_to 'Edit', edit_partida_path(@partida) %> |
<%= link_to 'Back', partidas_path %>